/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.InventoryControlWorkArea;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import Business.System.System;

/**
 *
 * @author krystinfalcone
 */
public class InventoryControlWorkAreaJPanel extends javax.swing.JPanel {

        private JPanel userProcessContainer;
        private UserAccount account;
        private Organization organization;
        private Enterprise enterprise;
        private System system;
        private JLabel purchaseFeedbackLabel;
    /**
     * Creates new form InventoryControlWorkAreaJPanel
     * @param userProcessContainer
     * @param account
     * @param organization
     * @param enterprise
     * @param system
     */
    public InventoryControlWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, System system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        
        this.purchaseFeedbackLabel = new javax.swing.JLabel(" ");
        purchaseFeedbackLabel.setForeground(Color.GREEN);
        purchasePanel.add(purchaseFeedbackLabel);
        
        setupTable();
        showPanel("card3");
        loadInventory();
    }
    private void setupTable() {
    tblInventory.setModel(new javax.swing.table.DefaultTableModel(
        new String[]{"Item ID", "Supplier", "Qty (barrels)", "Price/Barrel", "Total Cost", "Purchase Date", "Request ID"}, 0
    ));
}

    private void showPanel(String card) {
    java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
    cl.show(contentPanel, card);
}

    private void loadInventory() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblInventory.getModel();
    model.setRowCount(0);

    Business.Inventory.OilInventory inv = organization.getOilInventory();
    for (Business.Inventory.OilInventory.OilInventoryItem item : inv.getItems()) {
        model.addRow(new Object[]{
            item.getItemId(),
            item.getSupplier(),
            item.getQuantityBarrels(),
            String.format("$%.2f", item.getPricePerBarrel()),
            String.format("$%.2f", item.getTotalCost()),
            item.getPurchaseDate(),
            item.getLinkedRequestId()
        });
    }

    lblTotalBarrels.setText("Total Barrels: " + inv.getTotalBarrels());
    lblTotalCost.setText("Total Cost: $" + String.format("%.2f", inv.getTotalCost()));
    lblAvgPrice.setText("Avg Price/Barrel: $" + String.format("%.2f", inv.getAveragePricePerBarrel()));
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnInventoryReport = new javax.swing.JButton();
        btnRecordPurchase = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        purchasePanel = new javax.swing.JPanel();
        lblReqId = new javax.swing.JLabel();
        lblSupplier = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtReqId = new javax.swing.JTextField();
        txtSupplier = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnSubmitPurchase = new javax.swing.JButton();
        reportPanel = new javax.swing.JPanel();
        reportScrollPane = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        lblTotalBarrels = new javax.swing.JLabel();
        lblTotalCost = new javax.swing.JLabel();
        lblAvgPrice = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        btnInventoryReport.setText("Inventory Report");
        btnInventoryReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryReportActionPerformed(evt);
            }
        });

        btnRecordPurchase.setText("Record Purchase");
        btnRecordPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordPurchaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnInventoryReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(btnRecordPurchase)
                .addGap(181, 181, 181))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInventoryReport)
                    .addComponent(btnRecordPurchase))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        contentPanel.setLayout(new java.awt.CardLayout());

        lblReqId.setText("Approved Request ID:");

        lblSupplier.setText("Supplier:");

        lblQty.setText("Quantity (barrels):");

        lblPrice.setText("Price per Barrel:");

        txtReqId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReqIdActionPerformed(evt);
            }
        });

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        btnSubmitPurchase.setText("Record Purchase");
        btnSubmitPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitPurchaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout purchasePanelLayout = new javax.swing.GroupLayout(purchasePanel);
        purchasePanel.setLayout(purchasePanelLayout);
        purchasePanelLayout.setHorizontalGroup(
            purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchasePanelLayout.createSequentialGroup()
                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSubmitPurchase)
                    .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(purchasePanelLayout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblSupplier)
                                .addComponent(lblQty)
                                .addComponent(lblPrice))
                            .addGap(18, 18, 18)
                            .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSupplier)
                                .addComponent(txtQty)
                                .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, purchasePanelLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(lblReqId)
                            .addGap(18, 18, 18)
                            .addComponent(txtReqId))))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        purchasePanelLayout.setVerticalGroup(
            purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchasePanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReqId)
                    .addComponent(txtReqId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplier)
                    .addComponent(txtSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(purchasePanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblQty))
                    .addGroup(purchasePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnSubmitPurchase)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        contentPanel.add(purchasePanel, "card2");

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item ID", "Supplier", "Qty", "Price/Bbl", "Total", "Date"
            }
        ));
        reportScrollPane.setViewportView(tblInventory);

        lblTotalBarrels.setText("Total Barrels: 0");

        lblTotalCost.setText("Total Cost: $0.00");

        lblAvgPrice.setText("Avg Price / Barrel: $0.00");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPanelLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(reportScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addGap(51, 51, 51))
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalCost)
                            .addComponent(lblTotalBarrels)
                            .addComponent(lblAvgPrice))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(reportScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotalBarrels)
                .addGap(18, 18, 18)
                .addComponent(lblTotalCost)
                .addGap(18, 18, 18)
                .addComponent(lblAvgPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(31, 31, 31))
        );

        contentPanel.add(reportPanel, "card3");

        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtReqIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReqIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReqIdActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void btnSubmitPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitPurchaseActionPerformed
        try {
         String reqId = txtReqId.getText().trim();
            String supplier = txtSupplier.getText().trim();
            int qty = Integer.parseInt(txtQty.getText().trim());
            double price = Double.parseDouble(txtPrice.getText().trim());

            if (supplier.isEmpty() || qty <= 0 || price <= 0) {
            purchaseFeedbackLabel.setText("Please fill in all fields with valid values.");
            purchaseFeedbackLabel.setForeground(java.awt.Color.RED);
            return;
        }

            organization.getOilInventory().addPurchase(supplier, qty, price, reqId);

            purchaseFeedbackLabel.setText("Purchase recorded successfully!");
            purchaseFeedbackLabel.setForeground(java.awt.Color.GREEN);
            txtReqId.setText("");
            txtSupplier.setText("");
            txtQty.setText("");
            txtPrice.setText("");

    } catch (NumberFormatException e) {
        purchaseFeedbackLabel.setText("Please enter valid numbers for quantity and price.");
        purchaseFeedbackLabel.setForeground(java.awt.Color.RED);
    }
    }//GEN-LAST:event_btnSubmitPurchaseActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadInventory();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnInventoryReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryReportActionPerformed
        loadInventory();
        showPanel("card3");
    }//GEN-LAST:event_btnInventoryReportActionPerformed

    private void btnRecordPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordPurchaseActionPerformed
        showPanel("card2");
    }//GEN-LAST:event_btnRecordPurchaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventoryReport;
    private javax.swing.JButton btnRecordPurchase;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSubmitPurchase;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvgPrice;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblReqId;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblTotalBarrels;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JPanel purchasePanel;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JScrollPane reportScrollPane;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtReqId;
    private javax.swing.JTextField txtSupplier;
    // End of variables declaration//GEN-END:variables
}
