/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.LogisticsCorp;

/**
 *
 * @author lindq
 */
import Business.Enterprise.Enterprise;
import Business.Operations.RequestBoard;
import Business.Operations.ShipmentRequest;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class LogisticsAnalystWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private Business.System.System system;
    private RequestBoard rb;

    private DefaultTableModel shipmentModel;
    private DefaultTableModel routeModel;

    /**
     * Creates new form LogisticsAnalystWorkAreaJPanel1
     */
    public LogisticsAnalystWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount,
            Organization organization, Enterprise enterprise, Business.System.System system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        this.rb = system.getRequestBoard();

        lblRole.setText("Logistics Analyst  |  Fleet Management  |  " + enterprise.getName());
        lblUser.setText("Logged in: " + userAccount.getUserLoginName());

        shipmentModel = (DefaultTableModel) shipmentTable.getModel();
        routeModel = (DefaultTableModel) routeTable.getModel();

        shipmentModel.setRowCount(0);
        routeModel.setRowCount(0);

        refreshAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northStack = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        lblRole = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        metricsPanel = new javax.swing.JPanel();
        cardTotalShipments = new javax.swing.JPanel();
        lblTotalShipmentsTitle = new javax.swing.JLabel();
        lblTotalShipments = new javax.swing.JLabel();
        cardDelivered = new javax.swing.JPanel();
        lblDeliveredTitle = new javax.swing.JLabel();
        lblDelivered = new javax.swing.JLabel();
        cardInTransit = new javax.swing.JPanel();
        lblInTransitTitle = new javax.swing.JLabel();
        lblInTransit = new javax.swing.JLabel();
        cardTotalVolume = new javax.swing.JPanel();
        lblTotalVolumeTitle = new javax.swing.JLabel();
        lblTotalVolume = new javax.swing.JLabel();
        mainSplit = new javax.swing.JSplitPane();
        historyPane = new javax.swing.JPanel();
        lblHistoryTitle = new javax.swing.JLabel();
        scrollHistory = new javax.swing.JScrollPane();
        routeTable = new javax.swing.JTable();
        txnPane = new javax.swing.JPanel();
        lblTxnTitle = new javax.swing.JLabel();
        scrollTxn = new javax.swing.JScrollPane();
        shipmentTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        northStack.setLayout(new javax.swing.BoxLayout(northStack, javax.swing.BoxLayout.Y_AXIS));

        headerPanel.setBackground(new java.awt.Color(225, 245, 238));
        headerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(15, 110, 86)));

        lblRole.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRole.setForeground(new java.awt.Color(8, 80, 65));
        lblRole.setText("Logistics Analyst  |  Fleet Management  |  Enterprise");
        headerPanel.add(lblRole);

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(15, 110, 86));
        lblUser.setText("Logged in: username");
        headerPanel.add(lblUser);

        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnRefresh.setText("Refresh Report");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        headerPanel.add(btnRefresh);

        northStack.add(headerPanel);

        metricsPanel.setBackground(new java.awt.Color(240, 250, 246));
        metricsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 16, 10, 16));
        metricsPanel.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        cardTotalShipments.setBackground(new java.awt.Color(225, 245, 238));
        cardTotalShipments.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 225, 203)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        cardTotalShipments.setLayout(new java.awt.BorderLayout());

        lblTotalShipmentsTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblTotalShipmentsTitle.setForeground(new java.awt.Color(8, 80, 65));
        lblTotalShipmentsTitle.setText("Total Shipments");
        cardTotalShipments.add(lblTotalShipmentsTitle, java.awt.BorderLayout.NORTH);

        lblTotalShipments.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblTotalShipments.setText("0");
        cardTotalShipments.add(lblTotalShipments, java.awt.BorderLayout.CENTER);

        metricsPanel.add(cardTotalShipments);

        cardDelivered.setBackground(new java.awt.Color(225, 245, 238));
        cardDelivered.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 225, 203)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        cardDelivered.setLayout(new java.awt.BorderLayout());

        lblDeliveredTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblDeliveredTitle.setForeground(new java.awt.Color(8, 80, 65));
        lblDeliveredTitle.setText("Delivered");
        cardDelivered.add(lblDeliveredTitle, java.awt.BorderLayout.NORTH);

        lblDelivered.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblDelivered.setText("0");
        lblDelivered.setToolTipText("");
        cardDelivered.add(lblDelivered, java.awt.BorderLayout.CENTER);

        metricsPanel.add(cardDelivered);

        cardInTransit.setBackground(new java.awt.Color(225, 245, 238));
        cardInTransit.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 225, 203)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        cardInTransit.setLayout(new java.awt.BorderLayout());

        lblInTransitTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblInTransitTitle.setForeground(new java.awt.Color(8, 80, 65));
        lblInTransitTitle.setText("In Transit / Scheduled");
        cardInTransit.add(lblInTransitTitle, java.awt.BorderLayout.NORTH);

        lblInTransit.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblInTransit.setText("0");
        lblInTransit.setToolTipText("");
        cardInTransit.add(lblInTransit, java.awt.BorderLayout.CENTER);

        metricsPanel.add(cardInTransit);

        cardTotalVolume.setBackground(new java.awt.Color(225, 245, 238));
        cardTotalVolume.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 225, 203)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        cardTotalVolume.setLayout(new java.awt.BorderLayout());

        lblTotalVolumeTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblTotalVolumeTitle.setForeground(new java.awt.Color(8, 80, 65));
        lblTotalVolumeTitle.setText("Total Volume Handled");
        cardTotalVolume.add(lblTotalVolumeTitle, java.awt.BorderLayout.NORTH);

        lblTotalVolume.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblTotalVolume.setText("0 bbl");
        lblTotalVolume.setToolTipText("");
        cardTotalVolume.add(lblTotalVolume, java.awt.BorderLayout.CENTER);

        metricsPanel.add(cardTotalVolume);

        northStack.add(metricsPanel);

        add(northStack, java.awt.BorderLayout.NORTH);

        mainSplit.setDividerLocation(320);
        mainSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        mainSplit.setResizeWeight(0.65);

        historyPane.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(200, 196, 185)));
        historyPane.setLayout(new java.awt.BorderLayout());

        lblHistoryTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHistoryTitle.setText("Performance by Route");
        lblHistoryTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 4, 4, 0));
        historyPane.add(lblHistoryTitle, java.awt.BorderLayout.NORTH);

        scrollHistory.setPreferredSize(new java.awt.Dimension(0, 180));

        routeTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        routeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Route (Origin -> Destination)", "Shipments", "Volume (bbl)", "Delivered", "Pending"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        routeTable.setRowHeight(22);
        scrollHistory.setViewportView(routeTable);

        historyPane.add(scrollHistory, java.awt.BorderLayout.CENTER);

        mainSplit.setBottomComponent(historyPane);

        txnPane.setLayout(new java.awt.BorderLayout());

        lblTxnTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTxnTitle.setText("Full Shipment Log");
        lblTxnTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 4, 4, 0));
        txnPane.add(lblTxnTitle, java.awt.BorderLayout.NORTH);

        scrollTxn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        shipmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Shipment ID", "Volume (bbl)", "Origin", "Destination", "Scheduled", "Delivered", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        shipmentTable.setRowHeight(24);
        shipmentTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        shipmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shipmentTableMouseClicked(evt);
            }
        });
        scrollTxn.setViewportView(shipmentTable);
        if (shipmentTable.getColumnModel().getColumnCount() > 0) {
            shipmentTable.getColumnModel().getColumn(6).setResizable(false);
        }

        txnPane.add(scrollTxn, java.awt.BorderLayout.CENTER);

        mainSplit.setTopComponent(txnPane);

        add(mainSplit, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        //java.lang.System.out.println("Refresh clicked — transactions: " + rb.getTransactions().size());
        refreshAll();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void shipmentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shipmentTableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_shipmentTableMouseClicked

    private void refreshAll() {
        refreshShipmentTable();
        refreshRouteTable();
        refreshMetrics();
    }

    private void refreshShipmentTable() {
        shipmentModel.setRowCount(0);
        java.util.ArrayList<ShipmentRequest> list = rb.getShipmentRequests();
        for (int i = list.size() - 1; i >= 0; i--) {
            ShipmentRequest sh = list.get(i);
            shipmentModel.addRow(new Object[]{
                sh.getId(),
                String.format("%,.0f", sh.getVolume()),
                sh.getOrigin(),
                sh.getDestination(),
                sh.getScheduledDate(),
                sh.getDeliveredDate().isEmpty() ? "—" : sh.getDeliveredDate(),
                sh.getStatus()
            });
        }
    }

    private void refreshRouteTable() {
        routeModel.setRowCount(0);

        Map<String, double[]> map = new LinkedHashMap<>();

        for (ShipmentRequest sh : rb.getShipmentRequests()) {
            String route = sh.getOrigin() + " -> " + sh.getDestination();
            map.putIfAbsent(route, new double[]{0, 0, 0, 0});
            double[] s = map.get(route);
            s[0]++;
            s[1] += sh.getVolume();
            if ("DELIVERED".equals(sh.getStatus())) {
                s[2]++;
            } else {
                s[3]++;
            }
        }

        for (Map.Entry<String, double[]> entry : map.entrySet()) {
            double[] s = entry.getValue();
            routeModel.addRow(new Object[]{
                entry.getKey(),
                String.format("%.0f", s[0]),
                String.format("%,.0f", s[1]),
                String.format("%.0f", s[2]),
                String.format("%.0f", s[3])
            });
        }

        // Totals row
        if (!map.isEmpty()) {
            double tc = 0, tv = 0, td = 0, tp = 0;
            for (double[] s : map.values()) {
                tc += s[0];
                tv += s[1];
                td += s[2];
                tp += s[3];
            }
            routeModel.addRow(new Object[]{
                "TOTAL",
                String.format("%.0f", tc),
                String.format("%,.0f", tv),
                String.format("%.0f", td),
                String.format("%.0f", tp)
            });
        }
    }

    private void refreshMetrics() {
        java.util.ArrayList<ShipmentRequest> list = rb.getShipmentRequests();
        int delivered = 0, other = 0;
        double totalVol = 0;

        for (ShipmentRequest sh : list) {
            totalVol += sh.getVolume();
            if ("DELIVERED".equals(sh.getStatus())) {
                delivered++;
            } else {
                other++;
            }
        }

        lblTotalShipments.setText(String.valueOf(list.size()));
        lblDelivered.setText(String.valueOf(delivered));
        lblInTransit.setText(String.valueOf(other));
        lblTotalVolume.setText(String.format("%,.0f bbl", totalVol));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel cardDelivered;
    private javax.swing.JPanel cardInTransit;
    private javax.swing.JPanel cardTotalShipments;
    private javax.swing.JPanel cardTotalVolume;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel historyPane;
    private javax.swing.JLabel lblDelivered;
    private javax.swing.JLabel lblDeliveredTitle;
    private javax.swing.JLabel lblHistoryTitle;
    private javax.swing.JLabel lblInTransit;
    private javax.swing.JLabel lblInTransitTitle;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTotalShipments;
    private javax.swing.JLabel lblTotalShipmentsTitle;
    private javax.swing.JLabel lblTotalVolume;
    private javax.swing.JLabel lblTotalVolumeTitle;
    private javax.swing.JLabel lblTxnTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JSplitPane mainSplit;
    private javax.swing.JPanel metricsPanel;
    private javax.swing.JPanel northStack;
    private javax.swing.JTable routeTable;
    private javax.swing.JScrollPane scrollHistory;
    private javax.swing.JScrollPane scrollTxn;
    private javax.swing.JTable shipmentTable;
    private javax.swing.JPanel txnPane;
    // End of variables declaration//GEN-END:variables
}
