/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.LogisticsCorp;

/**
 *
 * @author lindq
 */
import Business.Enterprise.Enterprise;
import Business.Operations.RequestBoard;
import Business.Operations.ShipmentRequest;
import Business.Organization;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class TransportCoordinatorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private Business.System.System system;
    private RequestBoard rb;

    private DefaultTableModel shipmentModel;

    /**
     * Creates new form TransportCoordinatorWorkAreaJPanel1
     */
    public TransportCoordinatorWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount,
            Organization organization, Enterprise enterprise, Business.System.System system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        this.rb = system.getRequestBoard();

        lblRole.setText("Transport Coordinator  |  Shipment Operations  |  " + enterprise.getName());
        lblUser.setText("Logged in: " + userAccount.getUserLoginName());

        shipmentModel = (DefaultTableModel) shipmentTable.getModel();

        shipmentModel.setRowCount(0);

        refreshAll();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northStack = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        lblRole = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        metricsPanel = new javax.swing.JPanel();
        cardScheduled = new javax.swing.JPanel();
        lblScheduledTitle = new javax.swing.JLabel();
        lblScheduled = new javax.swing.JLabel();
        cardInTransit = new javax.swing.JPanel();
        lblInTransitTitle = new javax.swing.JLabel();
        lblInTransit = new javax.swing.JLabel();
        cardDelivered = new javax.swing.JPanel();
        lblDeliveredTitle = new javax.swing.JLabel();
        lblDelivered = new javax.swing.JLabel();
        cardTotalVolume = new javax.swing.JPanel();
        lblTotalVolumeTitle = new javax.swing.JLabel();
        lblTotalVolume = new javax.swing.JLabel();
        centerPane = new javax.swing.JPanel();
        lblShipmentTitle = new javax.swing.JLabel();
        scrollShipment = new javax.swing.JScrollPane();
        shipmentTable = new javax.swing.JTable();
        actionBar = new javax.swing.JPanel();
        lblNote = new javax.swing.JLabel();
        txtDeliveryNote = new javax.swing.JTextField();
        btnMarkInTransit = new javax.swing.JButton();
        btnMarkDelivered = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        northStack.setLayout(new javax.swing.BoxLayout(northStack, javax.swing.BoxLayout.Y_AXIS));

        headerPanel.setBackground(new java.awt.Color(225, 245, 238));
        headerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(15, 110, 86)));

        lblRole.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRole.setForeground(new java.awt.Color(8, 80, 65));
        lblRole.setText("Transport Coordinator  |  Shipment Operations  |  Enterprise");
        headerPanel.add(lblRole);

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(15, 110, 86));
        lblUser.setText("Logged in: username");
        headerPanel.add(lblUser);

        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        headerPanel.add(btnRefresh);

        northStack.add(headerPanel);

        metricsPanel.setBackground(new java.awt.Color(240, 250, 246));
        metricsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 16, 10, 16));
        metricsPanel.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        cardScheduled.setBackground(new java.awt.Color(225, 245, 238));
        cardScheduled.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 225, 203)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        cardScheduled.setLayout(new java.awt.BorderLayout());

        lblScheduledTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblScheduledTitle.setForeground(new java.awt.Color(8, 80, 65));
        lblScheduledTitle.setText("Scheduled");
        cardScheduled.add(lblScheduledTitle, java.awt.BorderLayout.NORTH);

        lblScheduled.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblScheduled.setText("0");
        cardScheduled.add(lblScheduled, java.awt.BorderLayout.CENTER);

        metricsPanel.add(cardScheduled);

        cardInTransit.setBackground(new java.awt.Color(214, 234, 248));
        cardInTransit.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 225, 203)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        cardInTransit.setLayout(new java.awt.BorderLayout());

        lblInTransitTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblInTransitTitle.setForeground(new java.awt.Color(8, 80, 65));
        lblInTransitTitle.setText("In Transit");
        cardInTransit.add(lblInTransitTitle, java.awt.BorderLayout.NORTH);

        lblInTransit.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblInTransit.setText("0");
        lblInTransit.setToolTipText("");
        cardInTransit.add(lblInTransit, java.awt.BorderLayout.CENTER);

        metricsPanel.add(cardInTransit);

        cardDelivered.setBackground(new java.awt.Color(214, 245, 214));
        cardDelivered.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 225, 203)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        cardDelivered.setLayout(new java.awt.BorderLayout());

        lblDeliveredTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblDeliveredTitle.setForeground(new java.awt.Color(8, 80, 65));
        lblDeliveredTitle.setText("Delivered");
        cardDelivered.add(lblDeliveredTitle, java.awt.BorderLayout.NORTH);

        lblDelivered.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblDelivered.setText("0");
        lblDelivered.setToolTipText("");
        cardDelivered.add(lblDelivered, java.awt.BorderLayout.CENTER);

        metricsPanel.add(cardDelivered);

        cardTotalVolume.setBackground(new java.awt.Color(237, 237, 230));
        cardTotalVolume.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 225, 203)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        cardTotalVolume.setLayout(new java.awt.BorderLayout());

        lblTotalVolumeTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblTotalVolumeTitle.setForeground(new java.awt.Color(8, 80, 65));
        lblTotalVolumeTitle.setText("Total Volume Dispatched");
        cardTotalVolume.add(lblTotalVolumeTitle, java.awt.BorderLayout.NORTH);

        lblTotalVolume.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblTotalVolume.setText("0 bbl");
        lblTotalVolume.setToolTipText("");
        cardTotalVolume.add(lblTotalVolume, java.awt.BorderLayout.CENTER);

        metricsPanel.add(cardTotalVolume);

        northStack.add(metricsPanel);

        add(northStack, java.awt.BorderLayout.NORTH);

        centerPane.setLayout(new java.awt.BorderLayout());

        lblShipmentTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblShipmentTitle.setText("Shipment Queue");
        lblShipmentTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 4, 4, 0));
        centerPane.add(lblShipmentTitle, java.awt.BorderLayout.NORTH);

        scrollShipment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        shipmentTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        shipmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Shipment ID", "Linked Sell Req", "Volume (bbl)", "Origin", "Destination", "Scheduled", "Delivered", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        shipmentTable.setRowHeight(24);
        shipmentTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        shipmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shipmentTableMouseClicked(evt);
            }
        });
        scrollShipment.setViewportView(shipmentTable);

        centerPane.add(scrollShipment, java.awt.BorderLayout.CENTER);

        actionBar.setBackground(new java.awt.Color(240, 250, 246));
        actionBar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(159, 225, 203)));

        lblNote.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNote.setText("Note: ");
        actionBar.add(lblNote);

        txtDeliveryNote.setColumns(25);
        txtDeliveryNote.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDeliveryNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeliveryNoteActionPerformed(evt);
            }
        });
        actionBar.add(txtDeliveryNote);

        btnMarkInTransit.setBackground(new java.awt.Color(214, 234, 248));
        btnMarkInTransit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMarkInTransit.setForeground(new java.awt.Color(12, 68, 124));
        btnMarkInTransit.setText("Mark as In Transit");
        btnMarkInTransit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkInTransitActionPerformed(evt);
            }
        });
        actionBar.add(btnMarkInTransit);

        btnMarkDelivered.setBackground(new java.awt.Color(214, 245, 214));
        btnMarkDelivered.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMarkDelivered.setForeground(new java.awt.Color(39, 80, 10));
        btnMarkDelivered.setText("Mark as Delivered");
        btnMarkDelivered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkDeliveredActionPerformed(evt);
            }
        });
        actionBar.add(btnMarkDelivered);

        centerPane.add(actionBar, java.awt.BorderLayout.SOUTH);

        add(centerPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:  
        refreshAll();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void shipmentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shipmentTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_shipmentTableMouseClicked

    private void btnMarkInTransitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkInTransitActionPerformed
        // TODO add your handling code here:
        handleStatusUpdate("IN_TRANSIT");
    }//GEN-LAST:event_btnMarkInTransitActionPerformed

    private void btnMarkDeliveredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkDeliveredActionPerformed
        // TODO add your handling code here:
        handleStatusUpdate("DELIVERED");
    }//GEN-LAST:event_btnMarkDeliveredActionPerformed

    private void txtDeliveryNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeliveryNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeliveryNoteActionPerformed

    private void refreshAll() {
        refreshShipmentTable();
        refreshMetrics();
    }

    private void refreshShipmentTable() {
        shipmentModel.setRowCount(0);
        ArrayList<ShipmentRequest> list = rb.getShipmentRequests();
        for (int i = list.size() - 1; i >= 0; i--) {
            ShipmentRequest sh = list.get(i);
            shipmentModel.addRow(new Object[]{
                sh.getId(),
                sh.getLinkedSellRequestId(),
                String.format("%,.0f", sh.getVolume()),
                sh.getOrigin(),
                sh.getDestination(),
                sh.getScheduledDate(),
                sh.getDeliveredDate().isEmpty() ? "—" : sh.getDeliveredDate(),
                sh.getStatus()
            });
        }
    }

    private void refreshMetrics() {
        int scheduled = 0, inTransit = 0, delivered = 0;
        double totalVolume = 0;

        for (ShipmentRequest sh : rb.getShipmentRequests()) {
            totalVolume += sh.getVolume();
            switch (sh.getStatus()) {
                case "SCHEDULED" ->
                    scheduled++;
                case "IN_TRANSIT" ->
                    inTransit++;
                case "DELIVERED" ->
                    delivered++;
            }
        }

        lblScheduled.setText(String.valueOf(scheduled));
        lblInTransit.setText(String.valueOf(inTransit));
        lblDelivered.setText(String.valueOf(delivered));
        lblTotalVolume.setText(String.format("%,.0f bbl", totalVolume));
    }

    private void handleStatusUpdate(String newStatus) {
        int row = shipmentTable.getSelectedRow();
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a shipment from the table.",
                    "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String shipId = (String) shipmentModel.getValueAt(row, 0);
        String current = (String) shipmentModel.getValueAt(row, 7);

        if ("DELIVERED".equals(current)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "This shipment has already been delivered.",
                    "Already Delivered", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if ("IN_TRANSIT".equals(newStatus) && "IN_TRANSIT".equals(current)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Shipment is already in transit.",
                    "No Change", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        for (ShipmentRequest sh : rb.getShipmentRequests()) {
            if (sh.getId().equals(shipId)) {
                sh.setStatus(newStatus);
                if ("DELIVERED".equals(newStatus)) {
                    sh.setDeliveredDate(LocalDate.now().toString());
                }
                break;
            }
        }

        javax.swing.JOptionPane.showMessageDialog(this,
                "Shipment " + shipId + " updated to " + newStatus + ".",
                "Status Updated", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        txtDeliveryNote.setText("");
        refreshAll();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionBar;
    private javax.swing.JButton btnMarkDelivered;
    private javax.swing.JButton btnMarkInTransit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel cardDelivered;
    private javax.swing.JPanel cardInTransit;
    private javax.swing.JPanel cardScheduled;
    private javax.swing.JPanel cardTotalVolume;
    private javax.swing.JPanel centerPane;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel lblDelivered;
    private javax.swing.JLabel lblDeliveredTitle;
    private javax.swing.JLabel lblInTransit;
    private javax.swing.JLabel lblInTransitTitle;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblScheduled;
    private javax.swing.JLabel lblScheduledTitle;
    private javax.swing.JLabel lblShipmentTitle;
    private javax.swing.JLabel lblTotalVolume;
    private javax.swing.JLabel lblTotalVolumeTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel metricsPanel;
    private javax.swing.JPanel northStack;
    private javax.swing.JScrollPane scrollShipment;
    private javax.swing.JTable shipmentTable;
    private javax.swing.JTextField txtDeliveryNote;
    // End of variables declaration//GEN-END:variables
}
