package ui.SystemAdminWorkArea.ManageSystem;

import Business.Enterprise.Enterprise;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.chart.BarChart;
import javafx.scene.chart.CategoryAxis;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.PieChart;
import javafx.scene.chart.XYChart;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author ben
 */
public class EnterpriseReportWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseReportWorkAreaJPanel
     */
    private JFXPanel fxPanel;              // Swing container for JavaFX
    private BarChart<String, Number> chart; // keep reference if you want to update later
    JPanel userProcessContainer;
    Business.System.System system;

    public EnterpriseReportWorkAreaJPanel(JPanel userProcessContainer, Business.System.System system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        chartContainerPanel.setLayout(new BorderLayout());
        // Put JavaFX inside the designer panel, NOT directly on "this"
        fxPanel = new JFXPanel();
        chartContainerPanel.removeAll();
        chartContainerPanel.add(fxPanel, BorderLayout.CENTER);
        chartContainerPanel.revalidate();
        chartContainerPanel.repaint();
        Platform.runLater(this::initChartsFx);
    }

    private void initChartsFx() {
        PieChart pie1 = new PieChart();
        pie1.setTitle("Enterprise Categories");

        var enterprises = system.getNetworkList().get(0).getEnterpriseDirectory();
        pie1.getData().clear();
        for (Enterprise e : enterprises) {
            pie1.getData().add(new PieChart.Data(e.toString(), 1)); // equal slices
        }

        fxPanel.setScene(new Scene(new javafx.scene.layout.BorderPane(pie1), 800, 450));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        chartContainerPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout chartContainerPanelLayout = new javax.swing.GroupLayout(chartContainerPanel);
        chartContainerPanel.setLayout(chartContainerPanelLayout);
        chartContainerPanelLayout.setHorizontalGroup(
            chartContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        chartContainerPanelLayout.setVerticalGroup(
            chartContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        add(chartContainerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        Platform.runLater(() -> fxPanel.setScene(null));

        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        userProcessContainer.revalidate();
        userProcessContainer.repaint();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel chartContainerPanel;
    // End of variables declaration//GEN-END:variables
}
