package ui.SystemAdminWorkArea.ManageSystem;

import Business.Enterprise.Enterprise;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.chart.BarChart;
import javafx.scene.chart.CategoryAxis;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.PieChart;
import javafx.scene.chart.XYChart;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author ben
 */
public class EnterpriseReportWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseReportWorkAreaJPanel
     */
    private JFXPanel fxPanel;              // Swing container for JavaFX
    private BarChart<String, Number> chart; // keep reference if you want to update later
    JPanel userProcessContainer;
    Business.System.System system;
    private JPanel fxHost;

    public EnterpriseReportWorkAreaJPanel(JPanel userProcessContainer, Business.System.System system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        // Make chartContainerPanel a stable BorderLayout container
        chartContainerPanel.removeAll();
        chartContainerPanel.setLayout(new BorderLayout());

        fxHost = new JPanel(new BorderLayout());
        chartContainerPanel.add(fxHost, BorderLayout.CENTER);

        fxPanel = new JFXPanel();
        fxHost.add(fxPanel, BorderLayout.CENTER);

        chartContainerPanel.revalidate();
        chartContainerPanel.repaint();
    }

    // Initialize (or re-init) JavaFX AFTER Swing component is attached
    @Override
    public void addNotify() {
        super.addNotify();
        Platform.runLater(() -> {
            if (fxPanel.getScene() == null) {
                initChartsFx();
            } else {
                // optional: refresh if data can change
                refreshPie();
            }
        });
    }

    private void initChartsFx() {
        PieChart pie = buildPie();
        fxPanel.setScene(new Scene(new BorderPane(pie), 800, 450));
    }

    private PieChart buildPie() {
        PieChart pie = new PieChart();
        pie.setTitle("Enterprise Categories");
        refreshPie(pie);
        return pie;
    }

    private void refreshPie() {
        // refresh existing pie if scene already created
        if (fxPanel.getScene() == null) {
            return;
        }
        BorderPane root = (BorderPane) fxPanel.getScene().getRoot();
        PieChart pie = (PieChart) root.getCenter();
        refreshPie(pie);
    }

    private void refreshPie(PieChart pie) {
        var enterprises = system.getNetworkList().get(0).getEnterpriseDirectory();
        pie.getData().clear();
        for (Enterprise e : enterprises) {
            pie.getData().add(new PieChart.Data(e.toString(), 1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        chartContainerPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout chartContainerPanelLayout = new javax.swing.GroupLayout(chartContainerPanel);
        chartContainerPanel.setLayout(chartContainerPanelLayout);
        chartContainerPanelLayout.setHorizontalGroup(
            chartContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        chartContainerPanelLayout.setVerticalGroup(
            chartContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        add(chartContainerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        // Stop FX rendering and POP this card so previous() behaves like Back
        Platform.runLater(() -> fxPanel.setScene(null));

        userProcessContainer.remove(this); // POP (important!)

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        userProcessContainer.revalidate();
        userProcessContainer.repaint();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel chartContainerPanel;
    // End of variables declaration//GEN-END:variables
}
