/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdminWorkArea.ManageSystem;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ben
 */
public class ManageEnterpriseWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Business.System.System system;
    UserAccount userAccount;
    Network network;
    Enterprise selectedEnterprise;

    public ManageEnterpriseWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Business.System.System system, Network network) {
        initComponents();
        lblEnterprise.setText("Manage Enterprise -- "+ network.toString() + " Network");
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.system = system;
        this.network = network;
        reloadTable();
    }

    public void reloadTable() {
        int rowCount = tblEnterprise.getRowCount();
        DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (Enterprise e : network.getEnterpriseDirectory()) {
            Object row[] = new Object[1];
            row[0] = e;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnterprise = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        btnCreateEnterprise = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtEnterpriseName = new javax.swing.JTextField();
        btnDeleteEnterprise = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblEnterprise.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        lblEnterprise.setText("Manage Enterprise");

        btnBack1.setText("<< Exit");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        btnNext.setText("Manage Org. by Enterprise >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Enterprise Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblEnterpriseMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblEnterprise);

        btnCreateEnterprise.setText("Create Enterprise");
        btnCreateEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEnterpriseActionPerformed(evt);
            }
        });

        jLabel2.setText("Enterprise Name:");

        btnDeleteEnterprise.setText("Delete Enterprise");
        btnDeleteEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEnterpriseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreateEnterprise)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDeleteEnterprise)
                                .addGap(18, 18, 18)
                                .addComponent(btnNext)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBack1)
                        .addComponent(lblEnterprise))
                    .addContainerGap(235, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateEnterprise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteEnterprise)
                    .addComponent(btnNext))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblEnterprise)
                    .addGap(241, 241, 241)
                    .addComponent(btnBack1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.first(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:

        if (selectedEnterprise == null) {
            JOptionPane.showMessageDialog(this, "Please select the Enterprise", "ERROR", ERROR_MESSAGE);
            return;
        }
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("CreateOrgWorkAreaJPanel", new ManageOrgWorkAreaJPanel(userProcessContainer, userAccount, system, network, selectedEnterprise));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnCreateEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEnterpriseActionPerformed
        // TODO add your handling code here:
        if (txtEnterpriseName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enterprise Name cannot be empty", "ERROR", ERROR_MESSAGE);
            return;
        }
        if(!txtEnterpriseName.getText().matches("[A-Za-z0-9]+")){
            JOptionPane.showMessageDialog(this, "Enterprise Name is not accept special characters", "ERROR", ERROR_MESSAGE);
            return;
        }
        network.newEnterprise(txtEnterpriseName.getText());
        reloadTable();
    }//GEN-LAST:event_btnCreateEnterpriseActionPerformed

    private void btnDeleteEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEnterpriseActionPerformed
        // TODO add your handling code here:
        if (selectedEnterprise == null) {
            JOptionPane.showMessageDialog(this, "Please select the Enterprise", "ERROR", ERROR_MESSAGE);
            return;
        }
        Boolean result = network.removeEnterprise(selectedEnterprise);
        if (!result) {
            JOptionPane.showMessageDialog(this, "Please remove the Org. under the target Enterprise", "ERROR", ERROR_MESSAGE);
            return;
        }
        reloadTable();
    }//GEN-LAST:event_btnDeleteEnterpriseActionPerformed

    private void tblEnterpriseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEnterpriseMousePressed
        // TODO add your handling code here:
        int size = tblEnterprise.getRowCount();
        int selectedrow = tblEnterprise.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > size - 1) {
            return;
        }
        selectedEnterprise = (Enterprise) tblEnterprise.getValueAt(selectedrow, 0);
        if (selectedEnterprise == null) {
            return;
        }
    }//GEN-LAST:event_tblEnterpriseMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCreateEnterprise;
    private javax.swing.JButton btnDeleteEnterprise;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTextField txtEnterpriseName;
    // End of variables declaration//GEN-END:variables
}
