/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdminWorkArea.ManageSystem;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import Business.System.System;
import java.awt.CardLayout;

/**
 *
 * @author ben
 */
public class ManageSystemWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSystemWorkAreaJPanel
     */
    JPanel userProcessContainer;
    System system;
    UserAccount userAccount;

    public ManageSystemWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, System system) {
        initComponents();
        lblManageSystem.setText("Manage System: " + system.getName());
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageSystem = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        btnManageNetwork = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblManageSystem.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        lblManageSystem.setText("Manage System");

        btnBack1.setText("<< Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        btnManageNetwork.setText("Manage Network");
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManageSystem)
                    .addComponent(btnBack1)
                    .addComponent(btnManageNetwork))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManageSystem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageNetwork)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(btnBack1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        ManageNetworkWorkAreaJPanel manageNetworkAreaJPanel = new ManageNetworkWorkAreaJPanel(userProcessContainer, userAccount, system );
        userProcessContainer.add("manageNetworkAreaJPanel", manageNetworkAreaJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageNetworkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JLabel lblManageSystem;
    // End of variables declaration//GEN-END:variables
}
