package ui.SystemAdminWorkArea.ManageSystem;

import Business.Enterprise.Enterprise;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.util.ArrayList;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.chart.BarChart;
import javafx.scene.chart.CategoryAxis;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.PieChart;
import javafx.scene.chart.XYChart;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author ben
 */
public class UserReportWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseReportWorkAreaJPanel
     */
    private JFXPanel fxPanel;              // Swing container for JavaFX
    private BarChart<String, Number> barChart;
    JPanel userProcessContainer;
    Business.System.System system;
    Enterprise selectedEnterprise;
    private CategoryAxis xAxis;
    private NumberAxis yAxis;

    public UserReportWorkAreaJPanel(JPanel userProcessContainer, Business.System.System system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        chartContainerPanel.setLayout(new BorderLayout());   // IMPORTANT
        for (Enterprise e : system.getNetworkList().get(0).getEnterpriseDirectory()) {
            cbbEnterprise.addItem(e.toString());
        }
        chartContainerPanel.removeAll();
        // Put JavaFX inside the designer panel, NOT directly on "this"
        fxPanel = new JFXPanel();
        chartContainerPanel.add(fxPanel, BorderLayout.CENTER);
        chartContainerPanel.revalidate();
        chartContainerPanel.repaint();
        Platform.runLater(this::initChartsFx);
    }

    private void initChartsFx() {

        selectedEnterprise = system.getNetworkList().get(0).getEnterpriseDirectory().get(0);

        xAxis = new CategoryAxis();
        xAxis.setLabel("Organization");

        yAxis = new NumberAxis();
        yAxis.setLabel("User count");

        barChart = new BarChart<>(xAxis, yAxis);
        barChart.setLegendVisible(false);
        barChart.setAnimated(false);

        BorderPane root = new BorderPane(barChart);
        root.setPadding(new Insets(10));

        fxPanel.setScene(new Scene(root, 800, 450));

        updateChart();
    }

    private void updateChart() {
        if (selectedEnterprise == null || barChart == null) {
            return;
        }

        barChart.setTitle("Users by Organization (under " + selectedEnterprise + " Enterprise)");

        XYChart.Series<String, Number> series = new XYChart.Series<>();

        var orgList = selectedEnterprise.getParticipatingunits();
        for (var org : orgList) {
            int userCount = org.getUserAccountDirectory().getUserAccountList().size();
            series.getData().add(new XYChart.Data<>(org.toString(), userCount));
        }

        barChart.getData().setAll(series); // this replaces existing series cleanly
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        chartContainerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbbEnterprise = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chartContainerPanelLayout = new javax.swing.GroupLayout(chartContainerPanel);
        chartContainerPanel.setLayout(chartContainerPanelLayout);
        chartContainerPanelLayout.setHorizontalGroup(
            chartContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chartContainerPanelLayout.setVerticalGroup(
            chartContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jLabel1.setText("Select Enterprise to display the Organizations user");

        cbbEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbbEnterpriseMousePressed(evt);
            }
        });
        cbbEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbEnterpriseActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbbEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(chartContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chartContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Platform.runLater(() -> fxPanel.setScene(null));

        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        userProcessContainer.revalidate();
        userProcessContainer.repaint();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbbEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbEnterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbEnterpriseActionPerformed

    private void cbbEnterpriseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbEnterpriseMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbbEnterpriseMousePressed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String sel = (String) cbbEnterprise.getSelectedItem();
        if (sel == null) {
            return;
        }

        for (Enterprise e : system.getNetworkList().get(0).getEnterpriseDirectory()) {
            if (sel.equals(e.toString())) {
                selectedEnterprise = e;
                break;
            }
        }

        Platform.runLater(() -> {
            // if scene was never created for some reason, create it
            if (fxPanel.getScene() == null) {
                initChartsFx();
            } else {
                updateChart();
            }
        });
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbbEnterprise;
    private javax.swing.JPanel chartContainerPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
