/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AnalystWorkArea;

import Business.Enterprise.Enterprise;
import Business.OilTrade.OilTradeRequest;
import Business.Organization;
import Business.Role.AnalystRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.System.System;

/**
 *
 * @author krystinfalcone
 */
public class AnalystWorkAreaJPanel extends javax.swing.JPanel {

    private javax.swing.JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private System system;

    private javax.swing.JLabel buyFeedbackLabel;
    private javax.swing.JLabel sellFeedbackLabel;

    /**
     * Creates new form AnalystWorkAreaJPanel
     * @param userProcessContainer
     * @param account
     * @param organization
     * @param enterprise
     * @param system
     */
    public AnalystWorkAreaJPanel(JPanel userProcessContainer,UserAccount account, Organization organization, Enterprise enterprise, System system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;

        buyFeedbackLabel = new javax.swing.JLabel(" ");
        buyFeedbackLabel.setForeground(Color.GREEN);
        buyPanel.add(buyFeedbackLabel);

        sellFeedbackLabel = new javax.swing.JLabel(" ");
        sellFeedbackLabel.setForeground(Color.GREEN);
        sellPanel.add(sellFeedbackLabel);

        populateSupplierCombo();
        setupTable();
        showPanel("card2");
    }
        private void populateSupplierCombo() {
            cmbSupplier.removeAllItems();
            cmbSupplier.addItem("UAE Oil Supplier");
            cmbSupplier.addItem("Saudi Arabia Supplier");
            cmbSupplier.addItem("Kuwait Supplier");
        }
        private void setupTable() {
            DefaultTableModel model = new DefaultTableModel(new String[]{"Request ID", "Type", "Price/Barrel", "Quantity", "Status"}, 0);
            tblRequests.setModel(model);
        }
        private void showPanel(String card) {
            CardLayout cl = (CardLayout) contentPanel.getLayout();
            cl.show(contentPanel, card);
        }
        private void loadMyRequests() {
            DefaultTableModel model = (DefaultTableModel) tblRequests.getModel();
            model.setRowCount(0);
            
            AnalystRole role = (AnalystRole) account.getAssociatedPersonProfile();
            String userId = role.getPerson().getPersonId();
            
            for (OilTradeRequest req : system.getNetworkList().get(0).getTradeRequestList().getRequestsByUser(userId)) {
            model.addRow(new Object[] {
                req.getRequestId(), req.getRequestType(), String.format("$%.2f", req.getPricePerBarrel()), req.getQuantityBarrels(), req.getStatus()
            });        
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBuy = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();
        btnMyRequests = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        buyPanel = new javax.swing.JPanel();
        lblBuyPrice = new javax.swing.JLabel();
        txtPriceField = new javax.swing.JTextField();
        lblBuyQty = new javax.swing.JLabel();
        txtQuantityField = new javax.swing.JTextField();
        btnSummitBuy = new javax.swing.JButton();
        sellPanel = new javax.swing.JPanel();
        lblSupplier = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox<>();
        lblSellPrice = new javax.swing.JLabel();
        txtSellPrice = new javax.swing.JTextField();
        lblSellQty = new javax.swing.JLabel();
        txtSellQuantityField = new javax.swing.JTextField();
        btnSubmitSell = new javax.swing.JButton();
        requestsPanel = new javax.swing.JPanel();
        myRequestsScrollPane = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        btnBuy.setText("Suggest Buy Price");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        btnSell.setText("Suggest Sell Price");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });

        btnMyRequests.setText("My Requests");
        btnMyRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyRequestsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnBuy)
                .addGap(95, 95, 95)
                .addComponent(btnSell)
                .addGap(128, 128, 128)
                .addComponent(btnMyRequests)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuy)
                    .addComponent(btnSell)
                    .addComponent(btnMyRequests))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        contentPanel.setLayout(new java.awt.CardLayout());

        lblBuyPrice.setText("Suggested Price per Barrel (USD):");

        lblBuyQty.setText("Quantity (barrels):");

        btnSummitBuy.setText("Submit Buy Suggestion");
        btnSummitBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSummitBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buyPanelLayout = new javax.swing.GroupLayout(buyPanel);
        buyPanel.setLayout(buyPanelLayout);
        buyPanelLayout.setHorizontalGroup(
            buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(buyPanelLayout.createSequentialGroup()
                        .addComponent(btnSummitBuy)
                        .addGap(412, 412, 412))
                    .addGroup(buyPanelLayout.createSequentialGroup()
                        .addGroup(buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBuyQty)
                            .addComponent(lblBuyPrice))
                        .addGap(18, 18, 18)
                        .addGroup(buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPriceField, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(txtQuantityField))
                        .addGap(359, 359, 359))))
        );
        buyPanelLayout.setVerticalGroup(
            buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuyPrice))
                .addGap(43, 43, 43)
                .addGroup(buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuyQty)
                    .addComponent(txtQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126)
                .addComponent(btnSummitBuy)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        contentPanel.add(buyPanel, "card2");

        lblSupplier.setText("Target Oil Supplier:");

        lblSellPrice.setText("Suggested Sell Price per Barrel (USD):");

        lblSellQty.setText("Quantity (barrels):");

        btnSubmitSell.setText("Submit Sell Suggestion");
        btnSubmitSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitSellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sellPanelLayout = new javax.swing.GroupLayout(sellPanel);
        sellPanel.setLayout(sellPanelLayout);
        sellPanelLayout.setHorizontalGroup(
            sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellPanelLayout.createSequentialGroup()
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sellPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSellPrice)
                            .addComponent(lblSupplier)))
                    .addGroup(sellPanelLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(lblSellQty)))
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sellPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnSubmitSell))
                    .addGroup(sellPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSellPrice)
                            .addComponent(cmbSupplier, 0, 161, Short.MAX_VALUE)
                            .addComponent(txtSellQuantityField))))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        sellPanelLayout.setVerticalGroup(
            sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplier)
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSellPrice)
                    .addComponent(txtSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSellQty)
                    .addComponent(txtSellQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(btnSubmitSell)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        contentPanel.add(sellPanel, "card3");

        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        myRequestsScrollPane.setViewportView(tblRequests);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout requestsPanelLayout = new javax.swing.GroupLayout(requestsPanel);
        requestsPanel.setLayout(requestsPanelLayout);
        requestsPanelLayout.setHorizontalGroup(
            requestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestsPanelLayout.createSequentialGroup()
                .addGroup(requestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(requestsPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(myRequestsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(requestsPanelLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(btnRefresh)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        requestsPanelLayout.setVerticalGroup(
            requestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestsPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(myRequestsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        contentPanel.add(requestsPanel, "card4");

        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        showPanel("card2");
    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        showPanel("card3");
    }//GEN-LAST:event_btnSellActionPerformed

    private void btnSummitBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSummitBuyActionPerformed
    try {
            double price = Double.parseDouble(txtPriceField.getText().trim());
            int qty = Integer.parseInt(txtQuantityField.getText().trim());

            if (price <= 0 || qty <= 0) {
                buyFeedbackLabel.setText("Please enter values greater than zero.");
                buyFeedbackLabel.setForeground(Color.RED);
                return;
            }

            AnalystRole role = (AnalystRole) account.getAssociatedPersonProfile();
            String requestedBy = role.getPerson().getPersonId();

            system.getNetworkList().get(0).getTradeRequestList().addRequest(
                organization.getName(),
                enterprise.getName(),
                "N/A",
                "N/A",
                OilTradeRequest.RequestType.BUY,
                price,
                qty,
                requestedBy
            );

            buyFeedbackLabel.setText("Buy suggestion submitted successfully!");
            buyFeedbackLabel.setForeground(Color.GREEN);
            txtPriceField.setText("");
            txtQuantityField.setText("");

        } catch (NumberFormatException e) {
            buyFeedbackLabel.setText("Please enter valid numbers.");
            buyFeedbackLabel.setForeground(Color.RED);
        }
    }//GEN-LAST:event_btnSummitBuyActionPerformed

    private void btnSubmitSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitSellActionPerformed
try {
            double price = Double.parseDouble(txtSellPrice.getText().trim());
            int qty = Integer.parseInt(txtSellQuantityField.getText().trim());
            String supplier = (String) cmbSupplier.getSelectedItem();

            if (price <= 0 || qty <= 0) {
                sellFeedbackLabel.setText("Please enter values greater than zero.");
                sellFeedbackLabel.setForeground(Color.RED);
                return;
            }

            AnalystRole role = (AnalystRole) account.getAssociatedPersonProfile();
            String requestedBy = role.getPerson().getPersonId();

            system.getNetworkList().get(0).getTradeRequestList().addRequest(
                organization.getName(),
                enterprise.getName(),
                "N/A",
                supplier,
                OilTradeRequest.RequestType.SELL,
                price,
                qty,
                requestedBy
            );

            sellFeedbackLabel.setText("Sell suggestion submitted successfully!");
            sellFeedbackLabel.setForeground(Color.GREEN);
            txtSellPrice.setText("");
            txtSellQuantityField.setText("");

        } catch (NumberFormatException e) {
            sellFeedbackLabel.setText("Please enter valid numbers.");
            sellFeedbackLabel.setForeground(Color.RED);
        }
    }//GEN-LAST:event_btnSubmitSellActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
    loadMyRequests();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnMyRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyRequestsActionPerformed
       showPanel("card4");
    }//GEN-LAST:event_btnMyRequestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnMyRequests;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSell;
    private javax.swing.JButton btnSubmitSell;
    private javax.swing.JButton btnSummitBuy;
    private javax.swing.JPanel buyPanel;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBuyPrice;
    private javax.swing.JLabel lblBuyQty;
    private javax.swing.JLabel lblSellPrice;
    private javax.swing.JLabel lblSellQty;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JScrollPane myRequestsScrollPane;
    private javax.swing.JPanel requestsPanel;
    private javax.swing.JPanel sellPanel;
    private javax.swing.JTable tblRequests;
    private javax.swing.JTextField txtPriceField;
    private javax.swing.JTextField txtQuantityField;
    private javax.swing.JTextField txtSellPrice;
    private javax.swing.JTextField txtSellQuantityField;
    // End of variables declaration//GEN-END:variables
}
