/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.UAEOilSupplier;

/**
 *
 * @author lindq
 */
import Business.Enterprise.Enterprise;
import Business.Operations.BuyRequest;
import Business.Operations.PriceSuggestion;
import Business.Operations.RequestBoard;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class OilAnalystWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OilAnalystWorkAreaJPanel
     */
    private static final double BREAK_EVEN = 61.20;

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private Business.System.System system;
    private RequestBoard rb;

    private DefaultTableModel buyRequestModel;
    private DefaultTableModel historyModel;

    public OilAnalystWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount,
            Organization organization, Enterprise enterprise, Business.System.System system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        this.rb = system.getRequestBoard();

        // Header text
        lblRole.setText("Oil Analyst  |  Oil Analytics Dept  |  " + enterprise.getName());
        lblUser.setText("Logged in: " + userAccount.getUserLoginName());
        lblBreakEven.setText(String.format("$%.2f", BREAK_EVEN));

        // table models
        buyRequestModel = (DefaultTableModel) buyRequestTable.getModel();
        historyModel = (DefaultTableModel) historyTable.getModel();
        buyRequestModel.setRowCount(0);
        historyModel.setRowCount(0);
        wireHistoryTableRenderer();


        // Initial data load
        refreshBuyRequestTable();
        refreshComboBox();
        refreshHistoryTable();

        buyRequestTable.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                if (!evt.getValueIsAdjusting()) {
                    int row = buyRequestTable.getSelectedRow();
                    if (row >= 0) {
                        String reqId = (String) buyRequestModel.getValueAt(row, 0);
                        cboBuyRequest.setSelectedItem(reqId);
                    }
                }
            }
        }
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northStack = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        lblRole = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        metricsPanel = new javax.swing.JPanel();
        cardMarketPrice = new javax.swing.JPanel();
        lblMarketPriceTitle = new javax.swing.JLabel();
        lblMarketPrice = new javax.swing.JLabel();
        card30DayAvg = new javax.swing.JPanel();
        lbl30DayAvgTitle = new javax.swing.JLabel();
        lblAvg30 = new javax.swing.JLabel();
        cardInventory = new javax.swing.JPanel();
        lblInventoryTitle = new javax.swing.JLabel();
        lblInventory = new javax.swing.JLabel();
        cardBreakEven = new javax.swing.JPanel();
        lblBreakEvenTitle = new javax.swing.JLabel();
        lblBreakEven = new javax.swing.JLabel();
        mainSplit = new javax.swing.JSplitPane();
        centerSplit = new javax.swing.JSplitPane();
        buyRequestPane = new javax.swing.JPanel();
        lblBuyRequestTitle = new javax.swing.JLabel();
        lblHint = new javax.swing.JLabel();
        scrollBuyRequest = new javax.swing.JScrollPane();
        buyRequestTable = new javax.swing.JTable();
        formPane = new javax.swing.JPanel();
        lblFormTitle = new javax.swing.JLabel();
        lblLinkedRequest = new javax.swing.JLabel();
        cboBuyRequest = new javax.swing.JComboBox<>();
        priceRow = new javax.swing.JPanel();
        priceField = new javax.swing.JPanel();
        lblPriceTitle = new javax.swing.JLabel();
        txtSuggestedPrice = new javax.swing.JTextField();
        marginField = new javax.swing.JPanel();
        lblMarginTitle = new javax.swing.JLabel();
        lblMargin = new javax.swing.JLabel();
        lblNotesTitle = new javax.swing.JLabel();
        scrollNotes = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        historyPane = new javax.swing.JPanel();
        lblHistoryTitle = new javax.swing.JLabel();
        scrollHistory = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        northStack.setLayout(new javax.swing.BoxLayout(northStack, javax.swing.BoxLayout.Y_AXIS));

        headerPanel.setBackground(new java.awt.Color(250, 238, 218));
        headerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(133, 79, 11)));

        lblRole.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRole.setForeground(new java.awt.Color(99, 56, 6));
        lblRole.setText("Oil Analyst  |  Oil Analytics Dept  |  Enterprise");
        headerPanel.add(lblRole);

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(133, 79, 11));
        lblUser.setText("Logged in: username");
        headerPanel.add(lblUser);

        northStack.add(headerPanel);

        metricsPanel.setBackground(new java.awt.Color(245, 245, 240));
        metricsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 16, 10, 16));
        metricsPanel.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        cardMarketPrice.setBackground(new java.awt.Color(237, 237, 230));
        cardMarketPrice.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 196, 185)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        cardMarketPrice.setLayout(new java.awt.BorderLayout());

        lblMarketPriceTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblMarketPriceTitle.setForeground(new java.awt.Color(95, 94, 90));
        lblMarketPriceTitle.setText("Market Price (live)");
        cardMarketPrice.add(lblMarketPriceTitle, java.awt.BorderLayout.NORTH);

        lblMarketPrice.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblMarketPrice.setText("$78.40");
        cardMarketPrice.add(lblMarketPrice, java.awt.BorderLayout.CENTER);

        metricsPanel.add(cardMarketPrice);

        card30DayAvg.setBackground(new java.awt.Color(237, 237, 230));
        card30DayAvg.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 196, 185)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        card30DayAvg.setLayout(new java.awt.BorderLayout());

        lbl30DayAvgTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lbl30DayAvgTitle.setForeground(new java.awt.Color(95, 94, 90));
        lbl30DayAvgTitle.setText("30-Day Average");
        card30DayAvg.add(lbl30DayAvgTitle, java.awt.BorderLayout.NORTH);

        lblAvg30.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblAvg30.setText("$76.15");
        lblAvg30.setToolTipText("");
        card30DayAvg.add(lblAvg30, java.awt.BorderLayout.CENTER);

        metricsPanel.add(card30DayAvg);

        cardInventory.setBackground(new java.awt.Color(237, 237, 230));
        cardInventory.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 196, 185)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        cardInventory.setLayout(new java.awt.BorderLayout());

        lblInventoryTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblInventoryTitle.setForeground(new java.awt.Color(95, 94, 90));
        lblInventoryTitle.setText("Inventory Available");
        cardInventory.add(lblInventoryTitle, java.awt.BorderLayout.NORTH);

        lblInventory.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblInventory.setText("42,500 bbl");
        lblInventory.setToolTipText("");
        cardInventory.add(lblInventory, java.awt.BorderLayout.CENTER);

        metricsPanel.add(cardInventory);

        cardBreakEven.setBackground(new java.awt.Color(237, 237, 230));
        cardBreakEven.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 196, 185)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        cardBreakEven.setLayout(new java.awt.BorderLayout());

        lblBreakEvenTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblBreakEvenTitle.setForeground(new java.awt.Color(95, 94, 90));
        lblBreakEvenTitle.setText("Break-even Cost");
        cardBreakEven.add(lblBreakEvenTitle, java.awt.BorderLayout.NORTH);

        lblBreakEven.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblBreakEven.setText("$61.20");
        lblBreakEven.setToolTipText("");
        cardBreakEven.add(lblBreakEven, java.awt.BorderLayout.CENTER);

        metricsPanel.add(cardBreakEven);

        northStack.add(metricsPanel);

        add(northStack, java.awt.BorderLayout.NORTH);

        mainSplit.setDividerLocation(300);
        mainSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        mainSplit.setResizeWeight(0.55);

        centerSplit.setDividerLocation(680);
        centerSplit.setResizeWeight(0.6);

        buyRequestPane.setLayout(new java.awt.BorderLayout());

        lblBuyRequestTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBuyRequestTitle.setText("Pending buy requests");
        lblBuyRequestTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 4, 4, 0));
        buyRequestPane.add(lblBuyRequestTitle, java.awt.BorderLayout.NORTH);

        lblHint.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblHint.setForeground(new java.awt.Color(133, 79, 11));
        lblHint.setText("Click a row to link it to your suggestion");
        lblHint.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        buyRequestPane.add(lblHint, java.awt.BorderLayout.SOUTH);

        scrollBuyRequest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buyRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Factory", "Volume (bbl)", "Their Ceiling", "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        buyRequestTable.setRowHeight(24);
        buyRequestTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        buyRequestTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyRequestTableMouseClicked(evt);
            }
        });
        scrollBuyRequest.setViewportView(buyRequestTable);

        buyRequestPane.add(scrollBuyRequest, java.awt.BorderLayout.CENTER);

        centerSplit.setLeftComponent(buyRequestPane);

        formPane.setBackground(new java.awt.Color(252, 251, 248));
        formPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 16, 12, 16));
        formPane.setLayout(new javax.swing.BoxLayout(formPane, javax.swing.BoxLayout.Y_AXIS));

        lblFormTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblFormTitle.setForeground(new java.awt.Color(99, 56, 6));
        lblFormTitle.setText("Submit Price Suggestion");
        formPane.add(lblFormTitle);

        lblLinkedRequest.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblLinkedRequest.setForeground(new java.awt.Color(95, 94, 90));
        lblLinkedRequest.setText("Linked Buy Request");
        formPane.add(lblLinkedRequest);

        cboBuyRequest.setAlignmentX(0.0F);
        cboBuyRequest.setAutoscrolls(true);
        cboBuyRequest.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        formPane.add(cboBuyRequest);

        priceRow.setAlignmentX(0.0F);
        priceRow.setMaximumSize(new java.awt.Dimension(2147483647, 60));
        priceRow.setOpaque(false);
        priceRow.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        priceField.setOpaque(false);
        priceField.setLayout(new java.awt.BorderLayout());

        lblPriceTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblPriceTitle.setForeground(new java.awt.Color(95, 94, 90));
        lblPriceTitle.setText("Suggested Price ($/bbl)");
        priceField.add(lblPriceTitle, java.awt.BorderLayout.NORTH);

        txtSuggestedPrice.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtSuggestedPrice.setText("79.50");
        txtSuggestedPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuggestedPriceActionPerformed(evt);
            }
        });
        txtSuggestedPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuggestedPriceKeyReleased(evt);
            }
        });
        priceField.add(txtSuggestedPrice, java.awt.BorderLayout.CENTER);

        priceRow.add(priceField);

        marginField.setOpaque(false);
        marginField.setLayout(new java.awt.BorderLayout());

        lblMarginTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblMarginTitle.setForeground(new java.awt.Color(95, 94, 90));
        lblMarginTitle.setText("Margin vs Break-even");
        marginField.add(lblMarginTitle, java.awt.BorderLayout.NORTH);

        lblMargin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMargin.setForeground(new java.awt.Color(59, 109, 17));
        lblMargin.setText("29.0%");
        lblMargin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 196, 185)));
        lblMargin.setOpaque(true);
        marginField.add(lblMargin, java.awt.BorderLayout.CENTER);

        priceRow.add(marginField);

        formPane.add(priceRow);

        lblNotesTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblNotesTitle.setForeground(new java.awt.Color(95, 94, 90));
        lblNotesTitle.setText("Justification Notes");
        formPane.add(lblNotesTitle);

        scrollNotes.setAlignmentX(0.0F);
        scrollNotes.setMaximumSize(new java.awt.Dimension(2147483647, 90));

        txtNotes.setColumns(20);
        txtNotes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNotes.setLineWrap(true);
        txtNotes.setRows(5);
        txtNotes.setWrapStyleWord(true);
        txtNotes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 196, 185)));
        scrollNotes.setViewportView(txtNotes);

        formPane.add(scrollNotes);

        btnSubmit.setBackground(new java.awt.Color(250, 238, 218));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(99, 56, 6));
        btnSubmit.setText("Submit to Oil Supplier Agent");
        btnSubmit.setMaximumSize(new java.awt.Dimension(2147483647, 36));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        formPane.add(btnSubmit);

        centerSplit.setRightComponent(formPane);

        mainSplit.setTopComponent(centerSplit);

        historyPane.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(200, 196, 185)));
        historyPane.setLayout(new java.awt.BorderLayout());

        lblHistoryTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHistoryTitle.setText("Suggestion History");
        lblHistoryTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 4, 4, 0));
        historyPane.add(lblHistoryTitle, java.awt.BorderLayout.NORTH);

        scrollHistory.setPreferredSize(new java.awt.Dimension(0, 180));

        historyTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Suggestion ID", "Date", "Price ($/bbl)", "Margin %", "Linked Request", "Status", "Supplier Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        historyTable.setRowHeight(22);
        scrollHistory.setViewportView(historyTable);

        historyPane.add(scrollHistory, java.awt.BorderLayout.CENTER);

        mainSplit.setBottomComponent(historyPane);

        add(mainSplit, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        handleSubmit();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void buyRequestTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyRequestTableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_buyRequestTableMouseClicked

    private void txtSuggestedPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuggestedPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuggestedPriceActionPerformed

    private void txtSuggestedPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuggestedPriceKeyReleased
        // TODO add your handling code here:
        updateMarginDisplay();
    }//GEN-LAST:event_txtSuggestedPriceKeyReleased

    private void updateMarginDisplay() {
        String text = txtSuggestedPrice.getText().trim();
        lblMargin.setText(computeMarginText(text));
        try {
            double p = Double.parseDouble(text);
            lblMargin.setForeground(p >= BREAK_EVEN
                    ? new Color(59, 109, 17)
                    : new Color(162, 45, 45));
        } catch (NumberFormatException ex) {
            lblMargin.setForeground(Color.GRAY);
        }
    }

    private String computeMarginText(String priceText) {
        try {
            double p = Double.parseDouble(priceText);
            if (p <= 0) {
                return "—";
            }
            double m = ((p - BREAK_EVEN) / BREAK_EVEN) * 100.0;
            return String.format("%.1f%%", m);
        } catch (NumberFormatException ex) {
            return "—";
        }
    }

    private void refreshBuyRequestTable() {
        buyRequestModel.setRowCount(0);
        for (BuyRequest br : rb.getBuyRequests()) {
            if ("OPEN".equals(br.getStatus())) {
                buyRequestModel.addRow(new Object[]{
                    br.getId(),
                    br.getFactoryName(),
                    String.format("%,.0f", br.getVolume()),
                    String.format("$%.2f", br.getPriceCeiling()),
                    br.getCreatedAt(),
                    br.getStatus()
                });
            }
        }
    }

    private void refreshComboBox() {
        cboBuyRequest.removeAllItems();
        cboBuyRequest.addItem("");
        for (BuyRequest br : rb.getBuyRequests()) {
            if ("OPEN".equals(br.getStatus())) {
                cboBuyRequest.addItem(br.getId());
            }
        }
    }

    private void refreshHistoryTable() {
        historyModel.setRowCount(0);
        ArrayList<PriceSuggestion> suggestions = rb.getPriceSuggestions();
        for (int i = suggestions.size() - 1; i >= 0; i--) {
            PriceSuggestion ps = suggestions.get(i);
            if (ps.getAnalystPersonId().equals(userAccount.getId())) {
                historyModel.addRow(new Object[]{
                    ps.getId(),
                    ps.getSubmittedAt(),
                    String.format("$%.2f", ps.getSuggestedPrice()),
                    String.format("%.1f%%", ps.getMarginPct()),
                    ps.getLinkedBuyRequestId(),
                    ps.getStatus(),
                    ps.getSupplierNote().isEmpty() ? "—" : ps.getSupplierNote()
                });
            }
        }
    }

  
private void handleSubmit() {
        String selectedReqId = (String) cboBuyRequest.getSelectedItem();
        if (selectedReqId == null || selectedReqId.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a linked buy request.",
                    "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String priceText = txtSuggestedPrice.getText().trim();
        if (priceText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter a suggested price.",
                    "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        double price;
        try {
            price = Double.parseDouble(priceText);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Suggested price must be a valid number.",
                    "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (price <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Price must be greater than zero.",
                    "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (price < BREAK_EVEN) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    String.format("Price $%.2f is below break-even ($%.2f). Cannot submit.",
                            price, BREAK_EVEN),
                    "Below Break-Even", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String notes = txtNotes.getText().trim();
        if (notes.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please provide justification notes.",
                    "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        double margin = ((price - BREAK_EVEN) / BREAK_EVEN) * 100.0;
        String today = LocalDate.now().toString();

        rb.newPriceSuggestion(
                userAccount.getId(),
                selectedReqId,
                price,
                margin,
                notes,
                today
        );

        javax.swing.JOptionPane.showMessageDialog(this,
                "Price suggestion submitted successfully.\nLinked to: " + selectedReqId,
                "Submitted", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        txtSuggestedPrice.setText("");
        txtNotes.setText("");
        if (cboBuyRequest.getItemCount() > 0) {
            cboBuyRequest.setSelectedIndex(0);
        }

        refreshHistoryTable();
    }

    private void wireHistoryTableRenderer() {
        historyTable.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table,
                    Object value, boolean isSelected, boolean hasFocus, int row, int col) {
                java.awt.Component c = super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, col);
                if (!isSelected) {
                    String status = (String) historyModel.getValueAt(row, 5);
                    switch (status) {
                        case "ACCEPTED" ->
                            c.setBackground(new Color(220, 245, 220));
                        case "REJECTED" ->
                            c.setBackground(new Color(250, 220, 220));
                        default ->
                            c.setBackground(Color.WHITE);
                    }
                }
                return c;
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JPanel buyRequestPane;
    private javax.swing.JTable buyRequestTable;
    private javax.swing.JPanel card30DayAvg;
    private javax.swing.JPanel cardBreakEven;
    private javax.swing.JPanel cardInventory;
    private javax.swing.JPanel cardMarketPrice;
    private javax.swing.JComboBox<String> cboBuyRequest;
    private javax.swing.JSplitPane centerSplit;
    private javax.swing.JPanel formPane;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel historyPane;
    private javax.swing.JTable historyTable;
    private javax.swing.JLabel lbl30DayAvgTitle;
    private javax.swing.JLabel lblAvg30;
    private javax.swing.JLabel lblBreakEven;
    private javax.swing.JLabel lblBreakEvenTitle;
    private javax.swing.JLabel lblBuyRequestTitle;
    private javax.swing.JLabel lblFormTitle;
    private javax.swing.JLabel lblHint;
    private javax.swing.JLabel lblHistoryTitle;
    private javax.swing.JLabel lblInventory;
    private javax.swing.JLabel lblInventoryTitle;
    private javax.swing.JLabel lblLinkedRequest;
    private javax.swing.JLabel lblMargin;
    private javax.swing.JLabel lblMarginTitle;
    private javax.swing.JLabel lblMarketPrice;
    private javax.swing.JLabel lblMarketPriceTitle;
    private javax.swing.JLabel lblNotesTitle;
    private javax.swing.JLabel lblPriceTitle;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUser;
    private javax.swing.JSplitPane mainSplit;
    private javax.swing.JPanel marginField;
    private javax.swing.JPanel metricsPanel;
    private javax.swing.JPanel northStack;
    private javax.swing.JPanel priceField;
    private javax.swing.JPanel priceRow;
    private javax.swing.JScrollPane scrollBuyRequest;
    private javax.swing.JScrollPane scrollHistory;
    private javax.swing.JScrollPane scrollNotes;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtSuggestedPrice;
    // End of variables declaration//GEN-END:variables
}
