/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.UAEOilSupplier;

/**
 *
 * @author lindq
 */
import Business.Enterprise.Enterprise;
import Business.Operations.OilTransaction;
import Business.Operations.RequestBoard;
import Business.Operations.SellRequest;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class OilInventoryWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private Business.System.System system;
    private RequestBoard rb;

    private DefaultTableModel txnModel;
    private DefaultTableModel breakdownModel;

    /**
     * Creates new form OilInventoryWorkAreaJPanel1
     */
    public OilInventoryWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount,
            Organization organization, Enterprise enterprise, Business.System.System system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        this.rb = system.getRequestBoard();

        lblRole.setText("Oil Inventory Control  |  Oil Inventory Dept  |  " + enterprise.getName());
        lblUser.setText("Logged in: " + userAccount.getUserLoginName());

        txnModel = (DefaultTableModel) txnTable.getModel();
        breakdownModel = (DefaultTableModel) historyTable.getModel();

        txnModel.setRowCount(0);
        breakdownModel.setRowCount(0);
        
        refreshAll();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northStack = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        lblRole = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        metricsPanel = new javax.swing.JPanel();
        cardTotalRevenue = new javax.swing.JPanel();
        lblTotalRevenueTitle = new javax.swing.JLabel();
        lblTotalRevenue = new javax.swing.JLabel();
        cardTotalVolume = new javax.swing.JPanel();
        lblTotalVolumeTitle = new javax.swing.JLabel();
        lblTotalVolume = new javax.swing.JLabel();
        cardTxnCount = new javax.swing.JPanel();
        lblTxnCountTitle = new javax.swing.JLabel();
        lblTxnCount = new javax.swing.JLabel();
        cardAvgPrice = new javax.swing.JPanel();
        lblAvgPriceTitle = new javax.swing.JLabel();
        lblAvgPrice = new javax.swing.JLabel();
        mainSplit = new javax.swing.JSplitPane();
        historyPane = new javax.swing.JPanel();
        lblHistoryTitle = new javax.swing.JLabel();
        scrollHistory = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        txnPane = new javax.swing.JPanel();
        lblTxnTitle = new javax.swing.JLabel();
        scrollTxn = new javax.swing.JScrollPane();
        txnTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        northStack.setLayout(new javax.swing.BoxLayout(northStack, javax.swing.BoxLayout.Y_AXIS));

        headerPanel.setBackground(new java.awt.Color(250, 238, 218));
        headerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(133, 79, 11)));

        lblRole.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRole.setForeground(new java.awt.Color(99, 56, 6));
        lblRole.setText("Oil Inventory Control  |  Oil Analytics Dept  |  UAE Oil Supplier");
        headerPanel.add(lblRole);

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(133, 79, 11));
        lblUser.setText("Logged in: username");
        headerPanel.add(lblUser);

        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btnRefresh.setText("Refresh Report");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        headerPanel.add(btnRefresh);

        northStack.add(headerPanel);

        metricsPanel.setBackground(new java.awt.Color(245, 245, 240));
        metricsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 16, 10, 16));
        metricsPanel.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        cardTotalRevenue.setBackground(new java.awt.Color(237, 237, 230));
        cardTotalRevenue.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 196, 185)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        cardTotalRevenue.setLayout(new java.awt.BorderLayout());

        lblTotalRevenueTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblTotalRevenueTitle.setForeground(new java.awt.Color(95, 94, 90));
        lblTotalRevenueTitle.setText("Total Revenue Earned");
        cardTotalRevenue.add(lblTotalRevenueTitle, java.awt.BorderLayout.NORTH);

        lblTotalRevenue.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTotalRevenue.setText("$0");
        cardTotalRevenue.add(lblTotalRevenue, java.awt.BorderLayout.CENTER);

        metricsPanel.add(cardTotalRevenue);

        cardTotalVolume.setBackground(new java.awt.Color(237, 237, 230));
        cardTotalVolume.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 196, 185)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        cardTotalVolume.setLayout(new java.awt.BorderLayout());

        lblTotalVolumeTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblTotalVolumeTitle.setForeground(new java.awt.Color(95, 94, 90));
        lblTotalVolumeTitle.setText("Total Volume Sold");
        cardTotalVolume.add(lblTotalVolumeTitle, java.awt.BorderLayout.NORTH);

        lblTotalVolume.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTotalVolume.setText("0 bbl");
        lblTotalVolume.setToolTipText("");
        cardTotalVolume.add(lblTotalVolume, java.awt.BorderLayout.CENTER);

        metricsPanel.add(cardTotalVolume);

        cardTxnCount.setBackground(new java.awt.Color(237, 237, 230));
        cardTxnCount.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 196, 185)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        cardTxnCount.setLayout(new java.awt.BorderLayout());

        lblTxnCountTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblTxnCountTitle.setForeground(new java.awt.Color(95, 94, 90));
        lblTxnCountTitle.setText("Completed Transactions");
        cardTxnCount.add(lblTxnCountTitle, java.awt.BorderLayout.NORTH);

        lblTxnCount.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTxnCount.setText("0");
        lblTxnCount.setToolTipText("");
        cardTxnCount.add(lblTxnCount, java.awt.BorderLayout.CENTER);

        metricsPanel.add(cardTxnCount);

        cardAvgPrice.setBackground(new java.awt.Color(237, 237, 230));
        cardAvgPrice.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 196, 185)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));
        cardAvgPrice.setLayout(new java.awt.BorderLayout());

        lblAvgPriceTitle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lblAvgPriceTitle.setForeground(new java.awt.Color(95, 94, 90));
        lblAvgPriceTitle.setText("Average Price per Barrel");
        cardAvgPrice.add(lblAvgPriceTitle, java.awt.BorderLayout.NORTH);

        lblAvgPrice.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblAvgPrice.setText("$0.00");
        lblAvgPrice.setToolTipText("");
        cardAvgPrice.add(lblAvgPrice, java.awt.BorderLayout.CENTER);

        metricsPanel.add(cardAvgPrice);

        northStack.add(metricsPanel);

        add(northStack, java.awt.BorderLayout.NORTH);

        mainSplit.setDividerLocation(340);
        mainSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        mainSplit.setResizeWeight(0.65);

        historyPane.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(200, 196, 185)));
        historyPane.setLayout(new java.awt.BorderLayout());

        lblHistoryTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHistoryTitle.setText("Revenue Breakdown by Factory");
        lblHistoryTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 4, 4, 0));
        historyPane.add(lblHistoryTitle, java.awt.BorderLayout.NORTH);

        scrollHistory.setPreferredSize(new java.awt.Dimension(0, 180));

        historyTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Factory (Destination)", "Transactions", "Volume Sold (bbl)", "Total Revenue", "Avg Price ($/bbl)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        historyTable.setRowHeight(22);
        scrollHistory.setViewportView(historyTable);

        historyPane.add(scrollHistory, java.awt.BorderLayout.CENTER);

        mainSplit.setBottomComponent(historyPane);

        txnPane.setLayout(new java.awt.BorderLayout());

        lblTxnTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTxnTitle.setText("Transaction Log - Oil Sales");
        lblTxnTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 4, 4, 0));
        txnPane.add(lblTxnTitle, java.awt.BorderLayout.NORTH);

        scrollTxn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Date", "Linked Sell Request", "Volume (bbl)", "Price ($/bbl)", "Total Revenue"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        txnTable.setRowHeight(24);
        txnTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        txnTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txnTableMouseClicked(evt);
            }
        });
        scrollTxn.setViewportView(txnTable);

        txnPane.add(scrollTxn, java.awt.BorderLayout.CENTER);

        mainSplit.setTopComponent(txnPane);

        add(mainSplit, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txnTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txnTableMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txnTableMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
         //java.lang.System.out.println("Refresh clicked — transactions: " + rb.getTransactions().size());
         refreshAll();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void refreshAll() {
        refreshTransactionTable();
        refreshBreakdownTable();
        refreshMetrics();
    }

    private void refreshTransactionTable() {
        txnModel.setRowCount(0);
        java.util.ArrayList<OilTransaction> list = rb.getTransactions();

        for (int i = list.size() - 1; i >= 0; i--) {
            OilTransaction t = list.get(i);
            txnModel.addRow(new Object[]{
                t.getId(),
                t.getCompletedAt(),
                t.getLinkedSellRequestId(),
                String.format("%,.0f", t.getVolume()),
                String.format("$%.2f", t.getPricePerBarrel()),
                String.format("$%,.2f", t.getTotalRevenue())
            });
        }
    }

    private void refreshBreakdownTable() {
        breakdownModel.setRowCount(0);

        Map<String, double[]> statsMap = new LinkedHashMap<>();

        for (OilTransaction t : rb.getTransactions()) {
            String destination = getFactoryNameForSellRequest(t.getLinkedSellRequestId());
            statsMap.putIfAbsent(destination, new double[]{0, 0, 0});
            double[] stats = statsMap.get(destination);
            stats[0] += 1;
            stats[1] += t.getVolume();
            stats[2] += t.getTotalRevenue();
        }

        for (Map.Entry<String, double[]> entry : statsMap.entrySet()) {
            double[] s = entry.getValue();
            double avgPrice = s[1] > 0 ? s[2] / s[1] : 0;
            breakdownModel.addRow(new Object[]{
                entry.getKey(),
                String.format("%.0f", s[0]),
                String.format("%,.0f", s[1]),
                String.format("$%,.2f", s[2]),
                String.format("$%.2f", avgPrice)
            });
        }

        // Totals row
        if (!statsMap.isEmpty()) {
            double totalTxn = 0, totalVol = 0, totalRev = 0;
            for (double[] s : statsMap.values()) {
                totalTxn += s[0];
                totalVol += s[1];
                totalRev += s[2];
            }
            double overallAvg = totalVol > 0 ? totalRev / totalVol : 0;
            breakdownModel.addRow(new Object[]{
                "TOTAL",
                String.format("%.0f", totalTxn),
                String.format("%,.0f", totalVol),
                String.format("$%,.2f", totalRev),
                String.format("$%.2f", overallAvg)
            });
        }
    }

    private String getFactoryNameForSellRequest(String sellRequestId) {
        for (SellRequest sr : rb.getSellRequests()) {
            if (sr.getId().equals(sellRequestId)) {
                var br = rb.findBuyRequest(sr.getLinkedBuyRequestId());
                if (br != null) {
                    return br.getFactoryName();
                }
            }
        }
        return "Unknown";
    }
    
    private void refreshMetrics() {
    java.util.ArrayList<OilTransaction> list = rb.getTransactions();

    if (list.isEmpty()) {
        lblTotalRevenue.setText("$0");
        lblTotalVolume.setText("0 bbl");
        lblTxnCount.setText("0");
        lblAvgPrice.setText("$0.00");
        return;
    }

    double totalRevenue = 0;
    double totalVolume = 0;

    for (OilTransaction t : list) {
        totalRevenue += t.getTotalRevenue();
        totalVolume += t.getVolume();
    }

    double avgPrice = totalVolume > 0 ? totalRevenue / totalVolume : 0;

    lblTotalRevenue.setText(String.format("$%,.0f", totalRevenue));
    lblTotalVolume.setText(String.format("%,.0f bbl", totalVolume));
    lblTxnCount.setText(String.valueOf(list.size()));
    lblAvgPrice.setText(String.format("$%.2f", avgPrice));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel cardAvgPrice;
    private javax.swing.JPanel cardTotalRevenue;
    private javax.swing.JPanel cardTotalVolume;
    private javax.swing.JPanel cardTxnCount;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel historyPane;
    private javax.swing.JTable historyTable;
    private javax.swing.JLabel lblAvgPrice;
    private javax.swing.JLabel lblAvgPriceTitle;
    private javax.swing.JLabel lblHistoryTitle;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTotalRevenue;
    private javax.swing.JLabel lblTotalRevenueTitle;
    private javax.swing.JLabel lblTotalVolume;
    private javax.swing.JLabel lblTotalVolumeTitle;
    private javax.swing.JLabel lblTxnCount;
    private javax.swing.JLabel lblTxnCountTitle;
    private javax.swing.JLabel lblTxnTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JSplitPane mainSplit;
    private javax.swing.JPanel metricsPanel;
    private javax.swing.JPanel northStack;
    private javax.swing.JScrollPane scrollHistory;
    private javax.swing.JScrollPane scrollTxn;
    private javax.swing.JPanel txnPane;
    private javax.swing.JTable txnTable;
    // End of variables declaration//GEN-END:variables
}
