/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FactoryManagerWorkArea;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.System.System;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author krystinfalcone
 */
public class FactoryManagerWorkAreaJPanel extends javax.swing.JPanel {
        private JPanel userProcessContainer;
        private UserAccount account;
        private Organization organization;
        private Enterprise enterprise;
        private System system;
        private JLabel lblFeedback;
       
    /**
     * Creates new form FactoryManagerWorkAreaJPanel
     * @param userProcessContainer
     * @param account
     * @param organization
     * @param enterprise
     * @param system
     */
    public FactoryManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, System system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        
        lblFeedback = new javax.swing.JLabel(" ");
        lblFeedback.setForeground(java.awt.Color.GREEN);
        pendingPanel.add(lblFeedback);
        
        setupTables();
        showPanel("card2");
        loadPendingRequests();
    }
    private void setupTables () {
       tblPending.setModel(new javax.swing.table.DefaultTableModel(new String[]{"Request ID", "Type", "From Org", "Price/Barrel", "Quantity", "Requested By", "Status"}, 0
       ));
       tblPending.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
       
       tblAllRequests.setModel(new javax.swing.table.DefaultTableModel(new String[]{"Request ID", "Type", "From Org", "Price/Barrel", "Quantity", "Requested By", "Status"}, 0 
               
       ));
    }
    private void showPanel(String card) {
        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, card);
    }
    
    private void loadPendingRequests() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPending.getModel();
        model.setRowCount(0);
        
        Business.OilTrade.OilTradeRequestList list = system.getNetworkList().get(0).getTradeRequestList();
        for (Business.OilTrade.OilTradeRequest req : list.getRequestsForEnterprise(enterprise.getName())) {
                if (req.getStatus() == Business.OilTrade.OilTradeRequest.RequestStatus.PENDING) {
                        model.addRow(new Object[]{
                    req.getRequestId(), req.getRequestType(), req.getFromOrganization(), String.format("$%.2f", req.getPricePerBarrel()), req.getQuantityBarrels(), req.getRequestedBy(), req.getStatus()
                });
            }
        }
    }
    private void loadAllRequests() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblAllRequests.getModel();
        model.setRowCount(0);
        
        Business.OilTrade.OilTradeRequestList list = system.getNetworkList().get(0).getTradeRequestList();
        for (Business.OilTrade.OilTradeRequest req : list.getRequestsForEnterprise(enterprise.getName())) {
            if (req.getStatus() == Business.OilTrade.OilTradeRequest.RequestStatus.PENDING) {
                model.addRow(new Object[]{
                    req.getRequestId(), req.getRequestType(), req.getFromOrganization(), String.format("$%.2f", req.getPricePerBarrel()), req.getQuantityBarrels(), req.getRequestedBy(), req.getStatus()
                });
        }
    }
    }
    private Business.OilTrade.OilTradeRequest getSelectedRequest() {
            int row = tblPending.getSelectedRow();
            if(row < 0) return null;
            String requestId = (String) tblPending.getValueAt (row, 0);
            return system.getNetworkList().get(0).getTradeRequestList().findRequest(requestId);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPending = new javax.swing.JButton();
        btnAllRequests = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        pendingPanel = new javax.swing.JPanel();
        pendingScrollPane = new javax.swing.JScrollPane();
        tblPending = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        lblNotes = new javax.swing.JLabel();
        txtNotes = new javax.swing.JTextField();
        btnReject = new javax.swing.JButton();
        allRequestsPanel = new javax.swing.JPanel();
        allRequestsScrollPane = new javax.swing.JScrollPane();
        tblAllRequests = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        btnPending.setText("Pending Requests");
        btnPending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendingActionPerformed(evt);
            }
        });

        btnAllRequests.setText("All Requests");
        btnAllRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllRequestsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnPending)
                .addGap(174, 174, 174)
                .addComponent(btnAllRequests)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPending)
                    .addComponent(btnAllRequests))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        contentPanel.setLayout(new java.awt.CardLayout());

        tblPending.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pendingScrollPane.setViewportView(tblPending);

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        lblNotes.setText("Review Notes:");

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pendingPanelLayout = new javax.swing.GroupLayout(pendingPanel);
        pendingPanel.setLayout(pendingPanelLayout);
        pendingPanelLayout.setHorizontalGroup(
            pendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingPanelLayout.createSequentialGroup()
                .addGroup(pendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pendingPanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(pendingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pendingPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblNotes)
                        .addGap(18, 18, 18)
                        .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(btnApprove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReject)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        pendingPanelLayout.setVerticalGroup(
            pendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(pendingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotes)
                    .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApprove)
                    .addComponent(btnReject))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        contentPanel.add(pendingPanel, "card2");

        tblAllRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        allRequestsScrollPane.setViewportView(tblAllRequests);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout allRequestsPanelLayout = new javax.swing.GroupLayout(allRequestsPanel);
        allRequestsPanel.setLayout(allRequestsPanelLayout);
        allRequestsPanelLayout.setHorizontalGroup(
            allRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allRequestsPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(allRequestsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, allRequestsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(124, 124, 124))
        );
        allRequestsPanelLayout.setVerticalGroup(
            allRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allRequestsPanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(allRequestsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnRefresh)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        contentPanel.add(allRequestsPanel, "card3");

        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadAllRequests();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAllRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllRequestsActionPerformed
        loadAllRequests();
        showPanel("card3");
    }//GEN-LAST:event_btnAllRequestsActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        Business.OilTrade.OilTradeRequest req = getSelectedRequest();
        if (req == null) {
            lblFeedback.setText("Please select a request first");
            lblFeedback.setForeground(Color.red);
            return;
        }
        req.setStatus(Business.OilTrade.OilTradeRequest.RequestStatus.APPROVED);
        req.setReviewNotes(txtNotes.getText().trim());
        lblFeedback.setText("Request " + req.getRequestId() + " approved.");
        lblFeedback.setForeground(Color.GREEN);
        txtNotes.setText("");
        loadPendingRequests();
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        Business.OilTrade.OilTradeRequest req = getSelectedRequest();
        if (req == null) {
            lblFeedback.setText("Please select a request first");
            lblFeedback.setForeground(Color.red);
            return;
        }
        req.setStatus(Business.OilTrade.OilTradeRequest.RequestStatus.REJECTED);
        req.setReviewNotes(txtNotes.getText().trim());
        lblFeedback.setText("Request " + req.getRequestId() + " rejected.");
        lblFeedback.setForeground(Color.GREEN);
        txtNotes.setText("");
        loadPendingRequests();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnPendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendingActionPerformed
        loadPendingRequests();
        showPanel("card2");
    }//GEN-LAST:event_btnPendingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allRequestsPanel;
    private javax.swing.JScrollPane allRequestsScrollPane;
    private javax.swing.JButton btnAllRequests;
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnPending;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReject;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JPanel pendingPanel;
    private javax.swing.JScrollPane pendingScrollPane;
    private javax.swing.JTable tblAllRequests;
    private javax.swing.JTable tblPending;
    private javax.swing.JTextField txtNotes;
    // End of variables declaration//GEN-END:variables
}
